float add(float num1,float num2);
float sub(float num1,float num2);
float product(float num1,float num2);
float div(float num1,float num2);
float sqr(float num1);
float k_m(float kb);
float m_k(float mb);
float m_g(float mb);
float g_m(float gb);
float r_d(float rupe);
float d_r(float dolr);
float r_e(float rupe);
float e_r(float euro);
float cm_m(float cm);
float m_cm(float m);
float m_km(float m);
float km_m(float km);